Private/magda/chosen report details
Abbion/Ankiette pull request #41
Opened 2022-05-23 10:07 UTC by madziarq

Widok zrobiony dla statycznych testowych wartości

2022-05-24 08:59 UTC, sweakpl requested changes
Niestety u mnie ekran przycina widok:

![obraz](https://user-images.githubusercontent.com/70141120/169991666-a770d0cc-e1f3-455f-aa50-b6d9745e2410.png)

Spowodowane jest to tym, że wysokości komponentów są wpisane na sztywno. Tu dla przyciętego diva `QuestionsBlock`:

```css
.QuestionsBlock{
    width: 1000px;
    height: 800px;    /* tu jest problem */
    margin: 60px;
    position: relative;

    background: rgba(242, 242, 242, 0.95);
    box-shadow: 4px 4px 40px 10px rgba(0, 0, 0, 0.25);
    border-radius: 56px;
}
```

Tak samo szerokość może się okazać problematyczna, jeśli kogoś ekran nie pomieści 1000 pikseli.

2022-05-24 21:00 UTC, madziarq commented
Poprawiłam trochę to skalowanie, dalej nie jest perfekcyjnie dla WSZYSTKICH przypadków. Jakiś bug się pojawia (po zmianie rozmiaru okna pojawia się suwaczek do przesuwania w osi X, po refreshu strony znika ale dalej można przesuwać w tej osi) ale nie do końca mogłam go zlokalizować. Jakby znalazło się coś bardzo istotnego do zmiany to dajcie znać bo nie chcę bardzo przedłużać robienia tego.

2022-05-25 13:20 UTC, sweakpl commented
No to rozjeżdżanie się pasków scrollowania jest spowodowane używaniem `vw` i `vh`. @Abbion kiedyś o tym pisał na discordzie albo messengerze.

2022-05-26 14:38 UTC, karolke99 commented
Dobra mergujmy to, potem sie poprawi takie pierdołki

2022-05-26 14:38 UTC, karolke99 approved these changes

2022-05-27 10:16 UTC, merged